name: waggs_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts:
  get_storage: ^2.0.3
  otp_text_field:
  dio:
  intl_phone_field:
  cached_network_image:
  syncfusion_flutter_sliders:
  flutter_rating_bar: ^4.0.1
  flutter_image_slideshow: ^0.1.2
  carousel_slider:
  flutter_svg: ^1.1.3
  shared_preferences: ^2.0.15
  http:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_native_splash:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo111.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/
